server:
  port: 8081

spring:
  redis:
    host: 124.223.27.13
    port: 6379
    password: 52wendyma
    connect-timeout: 5000
  datasource:
    username: root
    password: 52wendyma
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.223.27.13:3306/short_url?serverTimezone=GMT%2B8
    initialSize: 5
    minIdle: 5
    maxActive: 200